package com.projectvalis.util;

import java.util.Random;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * methods specific to running tests only. other utilities located in 
 * util packages.
 * 
 * @author snerd
 *
 */
public class TestHelper {

	static Logger LOGGER = LoggerFactory.getLogger(TestHelper.class);

	/**
	 * creates an [n] sized byte array populated with random bytes.
	 * 
	 * @param numBytesI
	 * @return populated array
	 */
	public static byte[] createByteArray(int numBytesI) {
		Random randy = new Random();
		byte[] generatedByteARR = new byte[numBytesI];

		for (int i = 0; i < numBytesI; i++) {
			generatedByteARR[i] = (byte) randy.nextInt(256);
		}

		String generatedBytesS = 
				ByteManipulation.getHexString(generatedByteARR);
		
		LOGGER.info("GENERATED BYTES ARE: " + generatedBytesS.toUpperCase());
		return generatedByteARR;
	}
	
	
	
	
	
	
}
